nameOverride: ""
fullnameOverride: ""

engine:
  # Set engine.config if you needa custom Dagger Engine config file
  # config: |
  #   debug = true
  #   insecure-entitlements = ["security.insecure"]
  #   [registry."registry:5000"]
  #     http = true
  #   [registry."docker.io"]
  #     mirrors = ["mirror.gcr.io"]
  resources:
    ## Example:
    ## limits:
    ##    cpu: 100m
    ##    memory: 128Mi
    ##
    limits: {}
    ## Examples:
    ## requests:
    ##    cpu: 100m
    ##    memory: 128Mi
    ##
    requests: {}
  image:
    repository: registry.dagger.io/engine
    # See https://github.com/dagger/dagger/blob/main/CHANGELOG.md for a list of available versions
    # tag: v0.8.7
  # tolerations:
  #   - effect: NoSchedule
  #     key: dagger-runner
  #     operator: Exists
  # affinity:
  #   nodeAffinity:
  #     requiredDuringSchedulingIgnoredDuringExecution:
  #       nodeSelectorTerms:
  #       - matchExpressions:
  #         - key: actions-runner
  #           operator: Exists
  readinessProbeSettings: 
    initialDelaySeconds: 5
    timeoutSeconds: 30
    periodSeconds: 15
    successThreshold: 1
    failureThreshold: 10
  terminationGracePeriodSeconds: 300


magicache:
  enabled: false
  url: https://api.dagger.cloud/magicache
  # token: <token>

# commonLabels Add labels to all the deployed resources
commonLabels:
  foo: bar
# commonAnnotations Add annotations to all the deployed resources
commonAnnotations: {}

serviceAccount:
  # Specifies whether a service account should be created
  create: true
  # Annotations to add to the service account
  annotations: {}
  # The name of the service account to use.
  # If not set and create is true, a name is generated using the fullname template
  name: ""